MIFA_DEFAULT_TARGET="www.academia.edu:443"
MIFA_DEFAULT_SNI="www.academia.edu"
MIFA_DEFAULT_PORTS="8443,50273"

install_core() {
  echo "Installing Xray..."

  # Install Xray if missing
  if ! command -v xray >/dev/null 2>&1; then
    bash -c "$(curl -fsSL https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
  fi

  mkdir -p /usr/local/etc/xray
  mkdir -p /var/log/xray
  mkdir -p /etc/mifa

  # Generate or refresh config/state if needed
  if [[ ! -f /usr/local/etc/xray/config.json ]]; then
    generate_config
  else
    echo "Xray config already exists: /usr/local/etc/xray/config.json"
    # Ensure state exists (best-effort)
    [[ -f /etc/mifa/state.env ]] || write_state_from_config || true
  fi

  systemctl enable xray
  systemctl restart xray

  echo "Core installed. State: /etc/mifa/state.env"
}

generate_config() {
  echo "Generating Xray Reality keys + config..."

  local KEYS PRIVATE PUBLIC UUID SHORT
KEYS=$(xray x25519)
PRIVATE=$(echo "$KEYS" | sed -n 's/^PrivateKey:[[:space:]]*//p; s/^Private:[[:space:]]*//p' | head -n1)

# Public key: best effort (depends on xray build flags)
PUBLIC=""
if xray x25519 -h 2>&1 | grep -q -- "-i"; then
  PUBLIC=$(xray x25519 -i "$PRIVATE" 2>/dev/null | sed -n 's/^PublicKey:[[:space:]]*//p; s/^Public:[[:space:]]*//p' | head -n1)
fi
  UUID=$(xray uuid)
  SHORT=$(openssl rand -hex 8)

  cp "$BASE_DIR/core/templates/config.template.json" /usr/local/etc/xray/config.json

python3 - <<PY
from pathlib import Path
cfg = Path("/usr/local/etc/xray/config.json")
s = cfg.read_text()
s = s.replace("__UUID__", "$UUID")
s = s.replace("__PRIVATE_KEY__", "$PRIVATE")
s = s.replace("__SHORT_ID__", "$SHORT")
cfg.write_text(s)
PY

  write_state_env "$PUBLIC" "$SHORT"
}

write_state_env() {
  local PUBLIC_KEY="$1"
  local SHORT_ID="$2"

  # Best-effort public IP; user can override later.
  local SERVER_IP
  SERVER_IP=$(curl -fsSL https://api.ipify.org || true)
  [[ -z "${SERVER_IP}" ]] && SERVER_IP="127.0.0.1"

  cat > /etc/mifa/state.env <<EOF
# Generated by MIFA platform installer
CONFIG_PATH=/usr/local/etc/xray/config.json
SERVER_IP=${SERVER_IP}
PUBLIC_KEY=${PUBLIC_KEY}
SHORT_ID=${SHORT_ID}
# Used by bot if not overridden
DEFAULT_SNI=www.github.com
PORTS=8443,50273
EOF

  chmod 600 /etc/mifa/state.env
}

write_state_from_config() {
  # Try to reconstruct a minimal state.env from existing config.json
  local CFG=/usr/local/etc/xray/config.json
  [[ -f "$CFG" ]] || return 1

  local SHORT
  SHORT=$(grep -oE '"shortIds"\s*:\s*\[[^\]]+\]' "$CFG" | head -n1 | grep -oE '"[0-9a-fA-F]+"' | head -n1 | tr -d '"' || true)

  cat > /etc/mifa/state.env <<EOF
# Reconstructed by MIFA platform installer
CONFIG_PATH=/usr/local/etc/xray/config.json
SERVER_IP=127.0.0.1
PUBLIC_KEY=
SHORT_ID=${SHORT}
DEFAULT_SNI=www.github.com
PORTS=8443,50273
EOF
  chmod 600 /etc/mifa/state.env
}
